language: java
sudo: false
dist: trusty
install: true
addons:
 sonarcloud:
   organization: "elliottdorta"
    token:
      secure: "f5fb8b931b1edcc391d84f9f583606460bfd4dae"
jdk:
  - oraclejdk8
 
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent package javadoc:javadoc sonar:sonar
cache:
 directories:
   - '$HOME/.m2/repository'
   - '$HOME/.sonar/cache'

on_success: always
on_failure: always
